version: "3"

services:
  course_backend:
    image: (IMAGES_NAME):latest
    ports:
      - "3001:3001"
    environment:
      NODE_ENV:
      PORT:
      DATABASE:
      JWT_SECRET:
      JWT_EXPIRES_IN:
      JWT_COOKIES_EXPIRES_IN:
      EMAIL_USERNAME:
      EMAIL_PASSWORD:
      EMAIL_HOST:
      EMAIL_PORT:
      GMAIL_USERNAME:
      GMAIL_PASSWORD:
      STRIP_PUBLISHABLE_KEY:
      STRIP_SCERET_KEY:
      CLIENT_DOMAIN:
